# NOTE: This file is used to hold variables that are specific to the DEV environment of the prg-shared pipeline.  
# Variables that will be shared across multiple pipelines should be stored in Azure DevOps variable libraries
variables:
- name: envAbbreviation
  value: dev
- name: envType
  value: dev
- name: sharedPrefix
  value: prg-$(envAbbreviation)-shared
- name: AksAgentVmSize
  value: Standard_B2s
- name: AksNodeResourceGroupName
  value: $(sharedPrefix)-aksnodes-rg
- name: AksSubnetName
  value: prg-aks-01
- name: AksVirtualNetworkAddressPrefix
  value: 10.0
- name: AksVnetName
  value: $(sharedPrefix)-aks-vnet
- name: AksVnetResourceGroupName
  value: $(resourceGroup)
- name: ReleaseEnvironmentName
  value: DEV
- name: ACRResourceGroup
  value: prg-$(envType)-app-sharedresources-rg
- name: AksDnsServiceIp
  value: 10.2.5.10
- name: AksKubernetesVersion
  value: 1.22.4
- name: AksRbacTenantId
  value: 893c6ab5-5aae-4706-be15-dc729e4f10e8
- name: AksRouteTableName
  value: aks-agentpool-42472566-routetable
- name: AksServiceCidr
  value: 10.2.5.0/24
- name: aksAppGatewayNetworkSecurityGroup
  value: prg-aks-ag-nsg
- name: aksAppGatewaySubnetName
  value: prg-aks-ag-01
- name: AksServiceName
  value: $(sharedPrefix)-aks
- name: aksAgentNodeCount
  value: 2
- name: resourceGroup
  value: $(sharedPrefix)-rg
- name: AksAadGroupObjectId
  value: "8c1dfbfb-72c3-4251-a99b-4162199499d8"
- name: AksAadAdminGroupName
  value: PRG AKS ADM DEV
- name: AksAdminUserObjectIds
  value: "cd7d7911-5261-48ea-9c8a-4472c8909219"
- name: AksPodReaderGroupObjectId
  value: "53fe00bb-f025-43cf-846c-55cf9c0c9450"
- name: AzureDevOpsUrl
  value: https://dev.azure.com/prg-cloud/
- name: AzureSubscriptionId
  value: f3b14109-a3de-4f54-9f58-46d891380a7e
- name: functionKey
  value: 
- name: keyVaultName
  value: $(sharedPrefix)-kv
- name: ParentBusinessTag
  value: Karis Ministries
- name: ServiceOfferingTag
  value: Karis Ministries Services
- name: EnvironmentTag
  value: Dev/Test
- name: sharedAksCluster
  value: $(sharedPrefix)-aks
- name: ContainerRegistryAdminUser
  value: prgdevappsharedcr